// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvUkzeXivAWYdsCc83LpFCT0VSbHfrk8I',
    appId: '1:33214102311:web:dbb19b06613ba5e24a4702',
    messagingSenderId: '33214102311',
    projectId: 'fitapp-84a14',
    authDomain: 'fitapp-84a14.firebaseapp.com',
    storageBucket: 'fitapp-84a14.firebasestorage.app',
    measurementId: 'G-ZNL0R2P7Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvb-23RBrMGEIk7gCF18Fhr4SLV5pPesg',
    appId: '1:33214102311:android:ca213d5aefd11a804a4702',
    messagingSenderId: '33214102311',
    projectId: 'fitapp-84a14',
    storageBucket: 'fitapp-84a14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXyUNYFJE2JfUUR8wwdzGpJyoJeLXPkk8',
    appId: '1:33214102311:ios:67d73e1d8caa50424a4702',
    messagingSenderId: '33214102311',
    projectId: 'fitapp-84a14',
    storageBucket: 'fitapp-84a14.firebasestorage.app',
    iosClientId: '33214102311-a95va4245drurmapnkjc41gc5omuesrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXyUNYFJE2JfUUR8wwdzGpJyoJeLXPkk8',
    appId: '1:33214102311:ios:67d73e1d8caa50424a4702',
    messagingSenderId: '33214102311',
    projectId: 'fitapp-84a14',
    storageBucket: 'fitapp-84a14.firebasestorage.app',
    iosClientId: '33214102311-a95va4245drurmapnkjc41gc5omuesrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvUkzeXivAWYdsCc83LpFCT0VSbHfrk8I',
    appId: '1:33214102311:web:60f086235d20b6734a4702',
    messagingSenderId: '33214102311',
    projectId: 'fitapp-84a14',
    authDomain: 'fitapp-84a14.firebaseapp.com',
    storageBucket: 'fitapp-84a14.firebasestorage.app',
    measurementId: 'G-L89GES5SZ6',
  );
}
